algorithm: pimodel
save_dir: ./saved_models/usb_cv/
save_name: pimodel_adaptiope_615_0_domain_align
resume: True
load_path: ./saved_models/usb_cv//pimodel_adaptiope_615_0_domain_align/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 20
num_train_iter: 20480
num_log_iter: 512
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 2560
num_labels: 615
uratio: 1
ema_m: 0.0
ulb_loss_ratio: 10
unsup_warm_up: 0.4
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch2_32
net_from_name: False
data_dir: ./data
dataset: adaptiope
train_sampler: RandomSampler
num_classes: 123
num_workers: 3
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10046
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth
domain_align: True
da_len: 32